# My application properties that I need / want
s3mirror:
  root_pattern: "TestRootPattern"
  mode:
    index: False
    mirror: False
  source: S3
  target: S3
  s3:
    access-key-id: "who"
    secret-access-key: "who"
    endpoint-override: http://localhost:9001

quarkus:
  jib:
    jvm-arguments:
      - "-Djava.util.logging.manager=org.jboss.logmanager.LogManager"
      - "-Xmx4G"
      - "-Xms4G"
  container-image:
    name: nephele-service
  swagger-ui:
    always-include: true

  redis:
    hosts: "redis://redis:6379"
  s3:
    endpoint-override: http://localhost:9001
    aws:
      credentials:
        type: default
      region: us-east-1


#"%dev":
#  s3mirror:
#    mode:
#      index: False
#      mirror: False
#    source: S3
#    target: S3
#    s3:
#      access-key-id: ""
#      secret-access-key: ""
#      endpoint-override: http://<host>:<port>
#  quarkus:
#    log:
#      level: INFO
#    redis:
#      hosts: "redis://localhost:6379"
#    s3:
#      endpoint-override: http://localhost:9001
#      aws:
#        credentials:
#          type: static
#          static-provider:
#            access-key-id: ""
#            secret-access-key: ""
